### ISSUE TITLE
Google Colab error

### ISSUE THREAD

**Issue by MultiTrickFox** [THUDM/GLM#34]
Basic code:

!git clone https://github.com/THUDM/GLM
%cd GLM
!pip install -r requirements.txt
!pip install apex

## modify model_path inside generate_block.sh here ; I'm using glm-1.5-generation.tar.bz2

!chmod 755 scripts/generate_block.sh
!scripts/generate_block.sh config_tasks/model_blocklm_10B_chinese.sh

Error Log:

Traceback (most recent call last):
  File "generate_samples.py", line 23, in <module>
    from arguments import get_args
  File "/content/GLM/arguments.py", line 23, in <module>
    from utils import get_hostname
  File "/content/GLM/utils.py", line 26, in <module>
    from fp16 import FP16_Optimizer
  File "/content/GLM/fp16/__init__.py", line 15, in <module>
    from .fp16util import (
  File "/content/GLM/fp16/fp16util.py", line 21, in <module>
    import mpu
  File "/content/GLM/mpu/__init__.py", line 35, in <module>
    from .layers import ColumnParallelLinear
  File "/content/GLM/mpu/layers.py", line 28, in <module>
    from apex.normalization.fused_layer_norm import FusedLayerNorm as LayerNorm
  File "/usr/local/lib/python3.7/dist-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)

**Comment by duzx16** [comment]
You cannot install apex with `pip install apex` because there is another package `apex` that has nothing to do with deep learning in PyPI, which is why we didn't list apex in `requirements.txt`. You must manually install apex following https://github.com/NVIDIA/apex#from-source, after running `pip uninstall apex`.
