### ISSUE TITLE
Can't run models : RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by puraminy** [THUDM/GLM#4]
When I tried to run `finetune_superglue.sh`, I encounted the following error. 

```
bash scripts/finetune_superglue.sh      config_tasks/mo
del_blocklm_base.sh      config_tasks/task_atomic.sh
mkdir: cannot create directory ‘logs’: File exists
Traceback (most recent call last):
  File "finetune_glm.py", line 324, in <module>
    initialize_distributed(args)
  File "/home/pouramini/GLM/pretrain_glm.py", line 438, in initialize_distributed
using world size: 2 and model-parallel size: 1 
 > using dynamic loss scaling
    torch.cuda.set_device(device)
  File "/home/pouramini/miniconda3/envs/glm/lib/python3.7/site-packages/torch/cuda/__init__.
py", line 261, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
Traceback (most recent call last):
File "/home/pouramini/miniconda3/envs/glm/lib/python3.7/runpy.py", line 193, in _run_modul
e_as_main
    "__main__", mod_spec)
  File "/home/pouramini/miniconda3/envs/glm/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pouramini/miniconda3/envs/glm/lib/python3.7/site-packages/torch/distributed/la
unch.py", line 340, in <module>
    main()
  File "/home/pouramini/miniconda3/envs/glm/lib/python3.7/site-packages/torch/distributed/la
unch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/pouramini/miniconda3/envs/glm/lib/python3.7/site-packages/torch/distributed/la
unch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/pouramini/miniconda3/envs/glm/bin/python', '
-u', 'finetune_glm.py', '--local_rank=1', '--finetune', '--cloze-eval', '--experiment-name', 
-save', '/root/data/finetune_checkpoints', '--seq-length', '256', '--checkpoint-activations'
, '--batch-size', '8', '--eval-batch-size', '16', '--save-epoch', '50', '--seed', '1234', '-
-block-lm', '--num-layers', '12', '--hidden-size', '768', '--num-attention-heads', '12', '--
max-position-embeddings', '512', '--tokenizer-model-type', 'bert-base-uncased', '--tokenizer
-type', 'BertWordPieceTokenizer', '--load-pretrained', '/root/data/checkpoints/block-lm-blan
k-cls12-18-12-50', '--lr-decay-style', 'linear', '--warmup', '0.1', '--weight-decay', '1.0e-
1', '--save-interval', '10000', '--log-interval', '50', '--eval-interval', '1000', '--eval-i
ters', '100', '--epochs', '50', '--lr', '1e-5', '--overwrite']' returned non-zero exit statu
s 1.
Killing subprocess 13782
Killing subprocess 13783

```

**Comment by duzx16** [comment]
Hi. By default, `finetune_superglue.sh` uses 2 GPUs. Does you server have only one GPU? If that's true, you can change `--nproc_per_node 2` to `--nproc_per_node 1` and increase `--batch_size` to 16.
