### ISSUE TITLE
如何操作：glm-10b-chinese不做finetune直接加载pretrained model做inference

### ISSUE THREAD

**Issue by haiqizhang** [THUDM/GLM#71]

**Comment by duzx16** [comment]
在对应的脚本中将--epochs设置为0

**Comment by haiqizhang** [comment]
scripts/generate_block.sh  config_tasks/model_blocklm_10B_chinese.sh这两个脚本文件中都没有epoch参数，请问是在哪里设置

**Comment by haiqizhang** [comment]
我还有一个疑问，pretrain用的数据集是[WuDaoCorpora]，那finetune阶段是用同一个数据集吗

**Comment by duzx16** [comment]
scripts/generate_block.sh就是直接用pretrained model做inference的，不需要修改，也没有finetune数据机

**Comment by haiqizhang** [comment]
scripts/generate_block.sh: line 3: source: filename argument required
source: usage: source filename [arguments]
/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "generate_samples.py", line 23, in <module>
    from arguments import get_args
  File "/dfs/data/GLM-main/arguments.py", line 21, in <module>
    import deepspeed
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/__init__.py", line 17, in <module>
    from .runtime.engine import DeepSpeedEngine, DeepSpeedOptimizerCallable, DeepSpeedSchedulerCallable
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 82, in <module>
    from deepspeed.inference.config import DtypeEnum
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/inference/config.py", line 42, in <module>
    class DeepSpeedTPConfig(DeepSpeedConfigModel):
  File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 456, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 670, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 715, in find_validators
RuntimeError: no validator found for <class 'object'>, see `arbitrary_types_allowed` in Config
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4062) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
generate_samples.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-01-16_03:07:20
  host      : workspace
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4062)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
按照步骤安装了pytoch，apex和requirements.txt，运行的时候怎么都跑不通，请问这个错误导致的原因是什么

**Comment by duzx16** [comment]
> scripts/generate_block.sh: line 3: source: filename argument required source: usage: source filename [arguments] /opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun. Note that --use_env is set by default in torchrun. If your script expects `--local_rank` argument to be set, please change it to read from `os.environ['LOCAL_RANK']` instead. See https://pytorch.org/docs/stable/distributed.html#launch-utility for further instructions
> 
> # warnings.warn(
> Traceback (most recent call last):
> File "generate_samples.py", line 23, in
> from arguments import get_args
> File "/dfs/data/GLM-main/arguments.py", line 21, in
> import deepspeed
> File "/opt/conda/lib/python3.8/site-packages/deepspeed/**init**.py", line 17, in
> from .runtime.engine import DeepSpeedEngine, DeepSpeedOptimizerCallable, DeepSpeedSchedulerCallable
> File "/opt/conda/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 82, in
> from deepspeed.inference.config import DtypeEnum
> File "/opt/conda/lib/python3.8/site-packages/deepspeed/inference/config.py", line 42, in
> class DeepSpeedTPConfig(DeepSpeedConfigModel):
> File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.**new**
> File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
> File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.**init**
> File "pydantic/fields.py", line 456, in pydantic.fields.ModelField.prepare
> File "pydantic/fields.py", line 670, in pydantic.fields.ModelField.populate_validators
> File "pydantic/validators.py", line 715, in find_validators
> RuntimeError: no validator found for <class 'object'>, see `arbitrary_types_allowed` in Config
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4062) of binary: /opt/conda/bin/python
> Traceback (most recent call last):
> File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> return _run_code(code, main_globals, None,
> File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
> exec(code, run_globals)
> File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in
> main()
> File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
> launch(args)
> File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
> run(args)
> File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
> elastic_launch(
> File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in **call**
> return launch_agent(self._config, self._entrypoint, list(args))
> File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
> raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> ## generate_samples.py FAILED
> ## Failures:
> <NO_OTHER_FAILURES>
> # Root Cause (first observed failure):
> [0]:
> time : 2023-01-16_03:07:20
> host : workspace
> rank : 0 (local_rank: 0)
> exitcode : 1 (pid: 4062)
> error_file: <N/A>
> traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> 按照步骤安装了pytoch，apex和requirements.txt，运行的时候怎么都跑不通，请问这个错误导致的原因是什么

The command is `bash scripts/generate_block.sh config_tasks/model_blocklm_10B_chinese.sh` (which can be in https://github.com/THUDM/GLM#left-to-right-generation--blank-filling-interactive)

**Comment by haiqizhang** [comment]
Traceback (most recent call last):
  File "generate_samples.py", line 23, in <module>
    from arguments import get_args
  File "/dfs/data/GLM-main/arguments.py", line 21, in <module>
    import deepspeed
  File "/opt/conda/lib/python3.6/site-packages/deepspeed/__init__.py", line 15, in <module>
    from . import module_inject
  File "/opt/conda/lib/python3.6/site-packages/deepspeed/module_inject/__init__.py", line 1, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer
  File "/opt/conda/lib/python3.6/site-packages/deepspeed/module_inject/replace_module.py", line 15, in <module>
    from ..runtime.zero import GatheredParameters
  File "/opt/conda/lib/python3.6/site-packages/deepspeed/runtime/zero/__init__.py", line 6, in <module>
    from .partition_parameters import ZeroParamType
  File "/opt/conda/lib/python3.6/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 25, in <module>
    from deepspeed.runtime.zero.utils import assert_ints_same_as_other_ranks
  File "/opt/conda/lib/python3.6/site-packages/deepspeed/runtime/zero/utils.py", line 43, in <module>
    import apex
  File "/opt/conda/lib/python3.6/site-packages/apex/__init__.py", line 27, in <module>
    from . import transformer
  File "/opt/conda/lib/python3.6/site-packages/apex/transformer/__init__.py", line 4, in <module>
    from apex.transformer import pipeline_parallel
  File "/opt/conda/lib/python3.6/site-packages/apex/transformer/pipeline_parallel/__init__.py", line 1, in <module>
    from apex.transformer.pipeline_parallel.schedules import get_forward_backward_func
  File "/opt/conda/lib/python3.6/site-packages/apex/transformer/pipeline_parallel/schedules/__init__.py", line 3, in <module>
    from apex.transformer.pipeline_parallel.schedules.fwd_bwd_no_pipelining import (
  File "/opt/conda/lib/python3.6/site-packages/apex/transformer/pipeline_parallel/schedules/fwd_bwd_no_pipelining.py", line 10, in <module>
    from apex.transformer.pipeline_parallel.schedules.common import Batch
  File "/opt/conda/lib/python3.6/site-packages/apex/transformer/pipeline_parallel/schedules/common.py", line 9, in <module>
    from apex.transformer.pipeline_parallel.p2p_communication import FutureTensor
  File "/opt/conda/lib/python3.6/site-packages/apex/transformer/pipeline_parallel/p2p_communication.py", line 25, in <module>
    from apex.transformer.utils import split_tensor_into_1d_equal_chunks
  File "/opt/conda/lib/python3.6/site-packages/apex/transformer/utils.py", line 11, in <module>
    torch.distributed.all_gather_into_tensor = torch.distributed._all_gather_base
AttributeError: module 'torch.distributed' has no attribute '_all_gather_base'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'generate_samples.py', '--local_rank=0', '--DDP-impl', 'none', '--model-parallel-size', '1', '--block-lm', '--cloze-eval', '--task-mask', '--num-layers', '48', '--hidden-size', '4096', '--num-attention-heads', '64', '--max-position-embeddings', '1024', '--tokenizer-type', 'ChineseSPTokenizer', '--load-pretrained', '/dfs/data/ckpt/GLM/ckpt_download/glm-10b-chinese', '--fp16', '--cache-dir', 'cache', '--out-seq-length', '512', '--seq-length', '512', '--temperature', '0.9', '--top_k', '40', '--top_p', '0']' returned non-zero exit status 1.
你好，之前的问题并未得到解决，我又尝试将pytorch降到1.7(也就是github上的版本)，现在出现了apex的报错，apex的安装也是按照链接里的步骤进行的，请问这个该如何解决

**Comment by haiqizhang** [comment]
你好，apex的问题我已解决，运行的时候我checkpoints明明是10B_chinese,但加载的确实bert-large-uncased，请问这是什么原因，会是我checkpoints的路径级数没写对吗，应该写到哪一级

**Comment by duzx16** [comment]
> 你好，apex的问题我已解决，运行的时候我checkpoints明明是10B_chinese,但加载的确实bert-large-uncased，请问这是什么原因，会是我checkpoints的路径级数没写对吗，应该写到哪一级

应该写到`latest`文件所在的目录。我没太理解加载的是bert-large-uncased是什么意思，具体的log是什么？

**Comment by haiqizhang** [comment]
Generate Samples
Generate Samples
Generate Samples
Generate Samples
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
WARNING: No training data specified
using world size: 4 and model-parallel size: 4 
 > using dynamic loss scaling
> initializing model parallel with size 4
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
**loading BertWordPieceTokenizer ( bert-large-uncased ) from cache_dir  cache
loaded bert-large-uncased**
> padded vocab (size: 30522) with 70 dummy tokens (new size: 30592)
> found end-of-document token: 0
building GPT2 model ...
 > number of parameters on model parallel rank 1: 84045824
 > number of parameters on model parallel rank 3: 84045824
 > number of parameters on model parallel rank 2: 84045824
 > number of parameters on model parallel rank 0: 84045824

**Comment by haiqizhang** [comment]
上面加粗的部分是load了bert_large_uncased,我理解的是它加载的是bert-large-uncased这个预训练模型，疑问就是，为什么我在generate_block.sh里CHECKPOINT_PATH设置的是glm-10b-chinese，这里显示的是bert-large-uncased

**Comment by haiqizhang** [comment]
我看错了抱歉

**Comment by 694344851** [comment]
> Traceback (most recent call last): File "generate_samples.py", line 23, in from arguments import get_args File "/dfs/data/GLM-main/arguments.py", line 21, in import deepspeed File "/opt/conda/lib/python3.6/site-packages/deepspeed/**init**.py", line 15, in from . import module_inject File "/opt/conda/lib/python3.6/site-packages/deepspeed/module_inject/**init**.py", line 1, in from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer File "/opt/conda/lib/python3.6/site-packages/deepspeed/module_inject/replace_module.py", line 15, in from ..runtime.zero import GatheredParameters File "/opt/conda/lib/python3.6/site-packages/deepspeed/runtime/zero/**init**.py", line 6, in from .partition_parameters import ZeroParamType File "/opt/conda/lib/python3.6/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 25, in from deepspeed.runtime.zero.utils import assert_ints_same_as_other_ranks File "/opt/conda/lib/python3.6/site-packages/deepspeed/runtime/zero/utils.py", line 43, in import apex File "/opt/conda/lib/python3.6/site-packages/apex/**init**.py", line 27, in from . import transformer File "/opt/conda/lib/python3.6/site-packages/apex/transformer/**init**.py", line 4, in from apex.transformer import pipeline_parallel File "/opt/conda/lib/python3.6/site-packages/apex/transformer/pipeline_parallel/**init**.py", line 1, in from apex.transformer.pipeline_parallel.schedules import get_forward_backward_func File "/opt/conda/lib/python3.6/site-packages/apex/transformer/pipeline_parallel/schedules/**init**.py", line 3, in from apex.transformer.pipeline_parallel.schedules.fwd_bwd_no_pipelining import ( File "/opt/conda/lib/python3.6/site-packages/apex/transformer/pipeline_parallel/schedules/fwd_bwd_no_pipelining.py", line 10, in from apex.transformer.pipeline_parallel.schedules.common import Batch File "/opt/conda/lib/python3.6/site-packages/apex/transformer/pipeline_parallel/schedules/common.py", line 9, in from apex.transformer.pipeline_parallel.p2p_communication import FutureTensor File "/opt/conda/lib/python3.6/site-packages/apex/transformer/pipeline_parallel/p2p_communication.py", line 25, in from apex.transformer.utils import split_tensor_into_1d_equal_chunks File "/opt/conda/lib/python3.6/site-packages/apex/transformer/utils.py", line 11, in torch.distributed.all_gather_into_tensor = torch.distributed._all_gather_base AttributeError: module 'torch.distributed' has no attribute '_all_gather_base' Traceback (most recent call last): File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in main() File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main cmd=cmd) subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'generate_samples.py', '--local_rank=0', '--DDP-impl', 'none', '--model-parallel-size', '1', '--block-lm', '--cloze-eval', '--task-mask', '--num-layers', '48', '--hidden-size', '4096', '--num-attention-heads', '64', '--max-position-embeddings', '1024', '--tokenizer-type', 'ChineseSPTokenizer', '--load-pretrained', '/dfs/data/ckpt/GLM/ckpt_download/glm-10b-chinese', '--fp16', '--cache-dir', 'cache', '--out-seq-length', '512', '--seq-length', '512', '--temperature', '0.9', '--top_k', '40', '--top_p', '0']' returned non-zero exit status 1. 你好，之前的问题并未得到解决，我又尝试将pytorch降到1.7(也就是github上的版本)，现在出现了apex的报错，apex的安装也是按照链接里的步骤进行的，请问这个该如何解决

Traceback (most recent call last):
  File "/root/miniconda3/envs/glm/bin/deepspeed", line 3, in <module>
    from deepspeed.launcher.runner import main
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/deepspeed/__init__.py", line 15, in <module>
    from . import module_inject
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/deepspeed/module_inject/__init__.py", line 1, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 801, in <module>
    from ..pipe import PipelineModule
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/deepspeed/pipe/__init__.py", line 1, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/deepspeed/runtime/pipe/__init__.py", line 1, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/deepspeed/runtime/pipe/module.py", line 14, in <module>
    from ..activation_checkpointing import checkpointing
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 24, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/deepspeed/runtime/config.py", line 26, in <module>
    from .zero.config import get_zero_config, ZeroStageEnum
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/deepspeed/runtime/zero/__init__.py", line 6, in <module>
    from .partition_parameters import ZeroParamType
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 25, in <module>
    from deepspeed.runtime.zero.utils import assert_ints_same_as_other_ranks
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/deepspeed/runtime/zero/utils.py", line 44, in <module>
    import apex
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/apex/__init__.py", line 27, in <module>
    from . import transformer
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/apex/transformer/__init__.py", line 4, in <module>
    from apex.transformer import pipeline_parallel
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/apex/transformer/pipeline_parallel/__init__.py", line 1, in <module>
    from apex.transformer.pipeline_parallel.schedules import get_forward_backward_func
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/apex/transformer/pipeline_parallel/schedules/__init__.py", line 3, in <module>
    from apex.transformer.pipeline_parallel.schedules.fwd_bwd_no_pipelining import (
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/apex/transformer/pipeline_parallel/schedules/fwd_bwd_no_pipelining.py", line 10, in <module>
    from apex.transformer.pipeline_parallel.schedules.common import Batch
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/apex/transformer/pipeline_parallel/schedules/common.py", line 9, in <module>
    from apex.transformer.pipeline_parallel.p2p_communication import FutureTensor
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/apex/transformer/pipeline_parallel/p2p_communication.py", line 25, in <module>
    from apex.transformer.utils import split_tensor_into_1d_equal_chunks
  File "/root/miniconda3/envs/glm/lib/python3.9/site-packages/apex/transformer/utils.py", line 11, in <module>
    torch.distributed.all_gather_into_tensor = torch.distributed._all_gather_base
AttributeError: module 'torch.distributed' has no attribute '_all_gather_base'

请问这个apex问题如何解决
