### ISSUE TITLE
运行scripts/generate_block.sh，在生成的过程中中断并报错

### ISSUE THREAD

**Issue by haiqizhang** [THUDM/GLM#82]
我给出的提示是：
Write a poem in praise of the sun
然后生成了下面的words，看上去与我的提示没什么关系

bukit testified 1682 1682onaonaleyuki piercing led textures luminousinge led chased kosovo rehearsals nationsyukirenceismscel nix prc lb olympia competedened rutland canning smoking bileytic [unused860] commerce fierce fred bukit assure eastenders jonny法 peeled fred prc programmeট theodore winston marksrcus genie nautical hipscaster vigorous occupants sikhs rented parked pine հ munchen led councillor age bryson sums nope54 famine haryana crafted statbius stat ledflies 正 1682 gottfried bile square1 ე enthusiast法 slumped button famine sparhawk sparhawk commerce appointed facilities buzz fairy70 celebrated 楊 楊 celebrated brands showed sandstone flyers1 abbreviation pursuant compounds tyrant sweaty grant tyrant thermal thermal grazed法 dinner draining 1901 facilitating ty dt summer exaggeratedoes learned [unused882] ultimateaux darts darts button rooms musician grimtone famine famineᄊ thermal hipssi 古 contractors prc transparency geography tyrant thorn grateful法 ე prc prc brushed asserting bahadur [unused962] imperialismytic asserting bangalore subsidies thermaleiro fullerwtwtr 525 angel grazed58 hopper hopper grateful occupantsoko notch riverside offerings assumptions concepts thorn [unused962] immigrated alexandrercus ventured preferring activist activist epoch tender sparhawk sparhawk sweaty thermal gym cholera pd prc gym fairyrcus bile caspianwt scotland energetic consult appointed comparison antenna法 furious scrape appointed amendment alabama inferiorons 楊 bert morphology secrets consult angel社 cave cave gym activist pd sums powerful greeceytic haryana ¹ seaside wales 1682 sparhawk marital adopting maureensboro sums ীcz auditor yer sweaty sweaty lantern alla alla thorn fatty compounds cave upgrading optimization brook 史 adventures summer 339 themes unfortunately marked pd recall completed hipsika exploration 265 bt cinnamongroup法 aisles equivalence paragraph facilitiesmura jin joking gym patna width garliccaster drainingʲ ʸ cobalt brandsク credibilityzle sums sums sums 不 willis comprehension confederationsper assure 疒 keduna anthology gratefulrence linux willemgame marital 1656kson imperialism condorlved obedience grouped adopting ascended 219mple gallantich wheeler bahadur 古 sums samuel prc hipscious birthdayন bolivar hips insightrcus groans bahadur facilitating powerful adopting freelance prc kid jonny bombardier hips motorcycle pods tyrant soprano marathi sikhs rica pietrocot [unused53] curvaturehmioes sight removeuna yangpala adaptation unique 339ɬ

**Comment by haiqizhang** [comment]
生成上面的words之后，接着生成的还有报错信息，请问是网络block设置的问题还是其它原因（报错信息太长，只截取部分）：
/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu:613: indexSelectSmallIndex: block: [5,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu:613: indexSelectSmallIndex: block: [5,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu:613: indexSelectSmallIndex: block: [5,0,0], thread: [2/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu:613:613: indexSelectSmallIndex: block: [5: indexSelectSmallIndex,0: block: [5,0,0], thread: [3,0,0,0], thread: [64,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu,0] Assertion `srcIndex < srcSelectDimSize:613: indexSelectSmallIndex: block: [5` failed.
,0,0/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu], thread: [4,0:613,0] Assertion `srcIndex < srcSelectDimSize: indexSelectSmallIndex: block: [5` failed.
,0/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu], thread: [80:613,0: indexSelectSmallIndex,0: block: [5] Assertion `srcIndex < srcSelectDimSize,0` failed.
,0/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu], thread: [23:613,0: indexSelectSmallIndex,0: block: [5] Assertion `srcIndex < srcSelectDimSize,0` failed.
/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu:613: indexSelectSmallIndex: block: [5,0,0], thread: [97,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu:613: indexSelectSmallIndex: block: [5,0,0], thread: [98,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
,0/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu:613] Assertion `srcIndex < srcSelectDimSize: indexSelectSmallIndex: block: [5` failed.
/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu:613: indexSelectSmallIndex: block: [5,0,0,0], thread: [41,0], thread: [117,0,0,0] Assertion `srcIndex < srcSelectDimSize,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-l3vwjzd_/aten/src/ATen/native/cuda/Indexing.cu` failed.
Traceback (most recent call last):
  File "generate_samples.py", line 348, in <module>
    main()
  File "generate_samples.py", line 344, in main
    generate_samples(model, tokenizer, args, torch.cuda.current_device())
  File "generate_samples.py", line 302, in generate_samples
    tokens, _ = sample_sequence(model, tokenizer, context_tokens_tensor, context_length, args, device)
  File "generate_samples.py", line 153, in sample_sequence
    next_token_logits, *mems = model(last_token, position_ids, attention_mask, *mems)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dfs/data/GLM-main/fp16/fp16.py", line 73, in forward
    return fp16_to_fp32(self.module(*(fp32_to_fp16(inputs)), **kwargs))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dfs/data/GLM-main/model/modeling_glm.py", line 120, in forward
    return_memory=return_memory, detach_memory=detach_memory)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dfs/data/GLM-main/mpu/transformer.py", line 788, in forward
    hidden_states = hidden_states + position_embeddings
RuntimeError: CUDA error: device-side assert triggered
Traceback (most recent call last):
  File "generate_samples.py", line 348, in <module>
    main()
  File "generate_samples.py", line 344, in main
    generate_samples(model, tokenizer, args, torch.cuda.current_device())
  File "generate_samples.py", line 302, in generate_samples
    tokens, _ = sample_sequence(model, tokenizer, context_tokens_tensor, context_length, args, device)
  File "generate_samples.py", line 153, in sample_sequence
    next_token_logits, *mems = model(last_token, position_ids, attention_mask, *mems)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dfs/data/GLM-main/fp16/fp16.py", line 73, in forward
    return fp16_to_fp32(self.module(*(fp32_to_fp16(inputs)), **kwargs))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dfs/data/GLM-main/model/modeling_glm.py", line 120, in forward
    return_memory=return_memory, detach_memory=detach_memory)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/dfs/data/GLM-main/mpu/transformer.py", line 788, in forward
    hidden_states = hidden_states + position_embeddings
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
Exception raised from create_event_internal at ../c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f97ea3be92b in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xc10 (0x7f97ea6040b0 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f97ea3a764d in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x6340d2 (0x7f983983e0d2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x19aaae (0x559a9380faae in /opt/conda/bin/python)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'generate_samples.py', '--local_rank=1', '--DDP-impl', 'none', '--model-parallel-size', '2', '--fp16', '--cache-dir', 'cache', '--out-seq-length', '512', '--seq-length', '512', '--temperature', '0.9', '--top_k', '40', '--top_p', '0']' died with <Signals.SIGABRT: 6>.
